<?php


namespace elleracompany\cookieconsent\records;

use craft\db\ActiveRecord;
use craft\records\Site;
use elleracompany\cookieconsent\CookieConsent;
use yii\behaviors\SluggableBehavior;
/**
 * This is the model class for table "auth_item".
 *
 * @property integer 	$id
 * @property boolean 	$required
 * @property boolean 	$store_ip
 * @property boolean 	$default
 * @property integer 	$site_id
 * @property integer 	$cookies
 * @property string 	$name
 * @property string 	$description
 * @property string		$slug
 */
class CookieGroup extends ActiveRecord
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		$behaviors = [
			[
				'class' => SluggableBehavior::className(),
				'attribute' => 'slugattribute',
				'slugAttribute' => 'slug',
				'ensureUnique' => true,
				'immutable' => true,
				'uniqueSlugGenerator' => function ($baseSlug, $iteration, $model)
				{
					return $baseSlug.'-'.$iteration;
				}
			],
		];
		return array_merge($behaviors, parent::behaviors());
	}

	/**
	 * @inheritdoc
	 */
	public function fields()
	{
		$fields = [
			'id',
			'name',
			'slug',
			'required',
			'cookies',
			'store_ip',
			'description',
			'site_id'
		];
		return array_merge($fields, parent::fields());
	}

	/**
	 * @inheritdoc
	 */
	public static function tableName(): string
	{
		return CookieConsent::COOKIE_GROUP_TABLE;
	}

	public function rules()
	{
		return [
			[['name', 'slug', 'description', 'cookies'], 'string'],
			[['site_id', 'description', 'name'], 'required'],
			[['required', 'store_ip', 'default'], 'boolean'],
			[['required', 'store_ip', 'default'], 'default', 'value' => 0],
			['site_id', 'integer']
		];
	}

	public function getSlugattribute()
	{
		return $this->site->handle.'-'.$this->name;
	}

	public function beforeSave($insert)
	{
		$this->stringifyCookies();
		return parent::beforeSave($insert);
	}

	public function afterSave($insert, $changedAttributes)
	{
		$this->unstringifyCookies();
		parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
	}

	public function beforeValidate()
	{
		$this->stringifyCookies();
		return parent::beforeValidate();
	}

	private function stringifyCookies()
	{
 		if(is_array($this->cookies)) $this->cookies = json_encode($this->cookies);
	}

	public function unstringifyCookies()
	{
		if(!is_array($this->cookies)) $this->cookies = json_decode($this->cookies, true);
	}

	public function getSite()
	{
		return $this->hasOne(Site::class, ['id' => 'site_id']);
	}

	public function getSiteSettings()
	{
		return $this->hasOne(SiteSettings::class, ['site_id' => 'site_id']);
	}
}
